// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Lemon.ErrorCode.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum LemonClientSdkErrorCode

/// 客户端SDK错误码
typedef GPB_ENUM(LemonClientSdkErrorCode) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  LemonClientSdkErrorCode_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /// 未知信息
  LemonClientSdkErrorCode_LemonClientSdkUnknown = 0,

  /// 成功
  LemonClientSdkErrorCode_LemonClientSdkSuccess = 10000000,

  /// 失败
  LemonClientSdkErrorCode_LemonClientSdkError = 10000001,
};

GPBEnumDescriptor *LemonClientSdkErrorCode_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL LemonClientSdkErrorCode_IsValidValue(int32_t value);

#pragma mark - Enum LemonServerErrorCode

/// 服务端错误码
typedef GPB_ENUM(LemonServerErrorCode) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  LemonServerErrorCode_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /// 未知信息
  LemonServerErrorCode_LemonServerUnknown = 0,

  /// 执行成功
  LemonServerErrorCode_LemonServerSuccess = 20000000,

  /// 服务器异常
  LemonServerErrorCode_LemonServerError = 20000001,

  /// Gateway Server错误码
  LemonServerErrorCode_LemonServerGatewayErrorAlreadyRegistry = 20001001,

  /// 已经绑定
  LemonServerErrorCode_LemonServerGatewayErrorAlreadyBind = 20001002,

  /// 未找到对应模块
  LemonServerErrorCode_LemonServerGatewayErrorNotFoundModule = 20001003,

  /// AppID无效
  LemonServerErrorCode_LemonServerGatewayErrorInvalidAppId = 20001004,

  /// 注册失败
  LemonServerErrorCode_LemonServerGatewayErrorRegistryFailed = 20001005,

  /// 绑定失败
  LemonServerErrorCode_LemonServerGatewayErrorBindFailed = 20001006,
};

GPBEnumDescriptor *LemonServerErrorCode_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL LemonServerErrorCode_IsValidValue(int32_t value);

#pragma mark - LemonErrorCodeRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface LemonErrorCodeRoot : GPBRootObject
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
