// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Lemon.CommandTypes.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum LemonModuleID

///
/// module id
typedef GPB_ENUM(LemonModuleID) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  LemonModuleID_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /// 未定义
  LemonModuleID_LemonMidUnknown = 0,

  /// 服务器之间的数据包
  LemonModuleID_LemonMidServer = 1,

  /// 网关服务
  LemonModuleID_LemonMidGateway = 2,

  /// 状态服务
  LemonModuleID_LemonMidStatus = 3,
};

GPBEnumDescriptor *LemonModuleID_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL LemonModuleID_IsValidValue(int32_t value);

#pragma mark - Enum LemonServerCmdID

////////////////////////////////////////////////////////////////////////////////////////
/// command id for server
typedef GPB_ENUM(LemonServerCmdID) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  LemonServerCmdID_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /// 未定义预留
  LemonServerCmdID_LemonCidServerUnknown = 0,
};

GPBEnumDescriptor *LemonServerCmdID_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL LemonServerCmdID_IsValidValue(int32_t value);

#pragma mark - Enum LemonGatewayCmdID

////////////////////////////////////////////////////////////////////////////////////////
/// command id for Gateway
typedef GPB_ENUM(LemonGatewayCmdID) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  LemonGatewayCmdID_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /// 未定义预留
  LemonGatewayCmdID_LemonCidGatewayUnknown = 0,

  /// 客户端向网关服务注册appId请求
  LemonGatewayCmdID_LemonCidGatewayRegistryReq = 1,

  /// 客户端向网关服务注册appId响应
  LemonGatewayCmdID_LemonCidGatewayRegistryResp = 2,

  /// 将链路与用户ID关联请求
  LemonGatewayCmdID_LemonCidGatewayBindUserReq = 5,

  /// 将链路与用户ID关联响应
  LemonGatewayCmdID_LemonCidGatewayBindUserResp = 6,

  /// 透传http消息请求
  LemonGatewayCmdID_LemonCidGatewayTransitHTTPMsgReq = 7,

  /// 透传http消息响应
  LemonGatewayCmdID_LemonCidGatewayTransitHTTPMsgResp = 8,

  /// Gateway Ping测试请求
  LemonGatewayCmdID_LemonCidGatewayPingReq = 9,

  /// Gateway Ping测试响应
  LemonGatewayCmdID_LemonCidGatewayPingResp = 10,

  /// Gateway主动向客户端发送广播消息
  LemonGatewayCmdID_LemonCidGatewayMsgNotify = 11,
  LemonGatewayCmdID_LemonCidGatewayMsgNotifyAck = 12,
};

GPBEnumDescriptor *LemonGatewayCmdID_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL LemonGatewayCmdID_IsValidValue(int32_t value);

#pragma mark - Enum HttpMethod

////////////////////////////////////////////////////////////////////////////////////////
typedef GPB_ENUM(HttpMethod) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  HttpMethod_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /// 未知请求方式
  HttpMethod_HTTPMethodUnknown = 0,

  /// Get请求
  HttpMethod_HTTPMethodGet = 1,

  /// Post请求
  HttpMethod_HTTPMethodPost = 2,
};

GPBEnumDescriptor *HttpMethod_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL HttpMethod_IsValidValue(int32_t value);

#pragma mark - LemonCommandTypesRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface LemonCommandTypesRoot : GPBRootObject
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
